# Generated by Django 2.2.2 on 2019-07-01 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=68)),
                ('last_name', models.CharField(max_length=68)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('birthday_date', models.DateField()),
                ('key_words', models.CharField(blank=True, max_length=68, null=True)),
                ('sales', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=68)),
                ('description', models.TextField(max_length=200)),
                ('reviews', models.TextField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, choices=[('ukr', 'Ukrainian'), ('eng', 'English'), ('grm', 'German'), ('frn', 'French')], default='ukr', max_length=3, null=True)),
                ('publication_date', models.DateField()),
                ('binding', models.CharField(choices=[('Soft', 'Soft binding'), ('Hard', 'Hard binding')], max_length=1)),
                ('iSBN', models.CharField(choices=[('9783161484100', '9783161484100'), ('2546854489720', '2546854489720'), ('7845124001454', '7845124001454'), ('6524408004012', '6524408004012')], max_length=13)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(null=True)),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(choices=[('inpr', 'in progress'), ('done', 'done'), ('canc', 'canceled')], max_length=4)),
                ('purchased_books', models.ManyToManyField(related_name='purchased_books', to='bs_api.Book')),
            ],
        ),
    ]
